### ISSUE TITLE
Support Visual Studio 2015

### ISSUE THREAD

**Issue by LinardAtTenForce** [ceztko/SccAutoSwitcher#2]
Any chance you could add support for VS2015?

**Comment by ceztko** [comment]
I don't have it and few chances I can have it soon. I can make a build that supports VS2015 on the Manifest and upload it so you can test it. IMO, it will work cause the extension is quite simple.

**Comment by LinardAtTenForce** [comment]
I would be glad to test it and provide feedback.

**Comment by Tdue21** [comment]
Just a thought, get VS2015 Community edition. It is free and supports extensions.
Besides that, I would be happy to test as well.

**Comment by grmrobertson** [comment]
Likewise I would be glad to test and provide feedback. I have VS2015 Community Edition.

**Comment by ceztko** [comment]
Ok, I released the 1.1.1 version with support for VS2015. I tested with Community Edition and it seems to work. Please, can you test it with Professional and Ultimate? I want to be sure before uploading to the visual studio gallery.

https://github.com/ceztko/SccAutoSwitcher/releases/tag/1.1.1

**Comment by ceztko** [comment]
Oh, there's no Ultimate VS anymore, it's called Enterprise. Reuploading shortly.

**Comment by ceztko** [comment]
Ok, uploaded 1.1.2

https://github.com/ceztko/SccAutoSwitcher/releases/tag/1.1.2

**Comment by LinardAtTenForce** [comment]
I tested version 1.1.2 and it seems to work.
I installed it on VS2015 Enterprise, opened some SVN and Git solutions and it automatically switched to the right source control plug-in.
