### ISSUE TITLE
Support for Perforce

### ISSUE THREAD

**Issue by klm1** [ceztko/SccAutoSwitcher#3]
Any plans to also support Perforce with this release?

**Comment by ceztko** [comment]
Unfortunately I don't know anything about perforce. Supporting another scc provider is easy as long as:
- the source control system store its data in a folder relative to the solution location (similarly to .git, .svn);
- there is proper scc identifiers (provider and package ids) in the plugin for that source control system;
- the scc provider doesn't conflict with other providers.

**Comment by yzhoholiev** [comment]
You can find some possible implementation in the pull request https://github.com/ceztko/SccAutoSwitcher/pull/5

**Comment by ceztko** [comment]
I merged Iurii Zhogoliev pull request and released version 1.2.0 that has VS2017 support as well.
